// <auto-generated />
namespace Test_Chatting.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Chatv1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Chatv1));
        
        string IMigrationMetadata.Id
        {
            get { return "202004050830123_Chat-v1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
